version: 2.1

jobs:
  build:
    docker:
      - image: cimg/openjdk:11.0.10
    steps:
      - checkout
      - run: ./mvnw test
      - run: ./mvnw package
      - run: sleep 100

workflows:
  pr:
    jobs:
      - build
